---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: ensure apache is at the latest version
    command: sh /tmp/test.sh creates=/tmp/another.sh
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest  
  - name: make sure apache is running
    service:
      name: httpd
      state: started