---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: ensure apache is at the latest version
    shell: /tmp/test.sh creates=/tmp/another.sh
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: /tmp/test.sh >> /tmp/somelog.txt
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest  
  - name: make sure apache is running
    service:
      name: httpd
      state: started