---
- hosts: all
  remote_user: root
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: ensure apache is at the latest version
    shell: /tmp/test.sh {{max_clients}} >> /tmp/tesh.log
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: /tmp/test.sh >> /tmp/somelog.txt creates=/tmp/somelog.txt
  - name: ensure apache is at the java version
    yum:
      name: java-1.8.0-openjdk-devel
      state: latest  
