---

- hosts: all
  vars: 
    name: Hussain
    language: ansible
  tasks:
  - name: Know date on machine
    commamd: date
      
  - name: execute a file with args
    command: /tmp/test.sh hussain
   
